version: '3'
services:
    api:
        build:
            context: .
            dockerfile: api/Dockerfile
        ports:
            - "8080:8080"
        networks:
            - mynetwork

    mongodb:
        image: mongo
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - ./data:/data/db
        networks:
            - mynetwork

networks:
    mynetwork:
