version: '3'
services:
    api:
        build:
            dockerfile: Dockerfile.api
        ports:
            - "8080:8080"
        depends_on:
            - scrapper
        networks:
            - mynetwork

    scrapper:
        build:
            dockerfile: Dockerfile.scrapper
        ports:
            - "50051:50051"
        depends_on:
            - database
        networks:
            - mynetwork

    database:
        build:
            dockerfile: Dockerfile.database
        ports:
            - "50052:50052"
        depends_on:
            - mongodb
        networks:
            - mynetwork

    mongodb:
        image: mongo:latest
        ports:
            - "27018:27017"
        volumes:
            - mongodb_data:/data/db
        networks:
            - mynetwork

networks:
    mynetwork:

volumes:
    mongodb_data: