# Use the official Golang base image
FROM golang:1.20-alpine3.18

# Set the working directory inside the container
WORKDIR /app

# Copy the Go mod and sum files
COPY go.mod go.sum ./

# Download Go dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go application
RUN go build -o scrapper ./cmd/scrapper

# Expose the desired port
EXPOSE 50051

# Define the command to run the Go application
CMD ["./scrapper"]
